// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Pagamento_screen_init(void)
{
    ui_Pagamento = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pagamento, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pagamento, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pagamento, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_expresso1 = lv_img_create(ui_Pagamento);
    lv_img_set_src(ui_expresso1, &ui_img_expresso_png);
    lv_obj_set_width(ui_expresso1, LV_SIZE_CONTENT);   /// 69
    lv_obj_set_height(ui_expresso1, LV_SIZE_CONTENT);    /// 89
    lv_obj_set_x(ui_expresso1, -100);
    lv_obj_set_y(ui_expresso1, -31);
    lv_obj_set_align(ui_expresso1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_expresso1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_expresso1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_expresso1, 400);

    ui_lungo1 = lv_img_create(ui_Pagamento);
    lv_img_set_src(ui_lungo1, &ui_img_lungo_png);
    lv_obj_set_width(ui_lungo1, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_lungo1, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_lungo1, -100);
    lv_obj_set_y(ui_lungo1, -33);
    lv_obj_set_align(ui_lungo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lungo1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lungo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lungo1, 400);

    ui_LabelExpresso1 = lv_label_create(ui_Pagamento);
    lv_obj_set_width(ui_LabelExpresso1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelExpresso1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelExpresso1, -100);
    lv_obj_set_y(ui_LabelExpresso1, 50);
    lv_obj_set_align(ui_LabelExpresso1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelExpresso1, "Expresso");
    lv_obj_add_flag(ui_LabelExpresso1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_decor(ui_LabelExpresso1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExpresso1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLungo1 = lv_label_create(ui_Pagamento);
    lv_obj_set_width(ui_LabelLungo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLungo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLungo1, -100);
    lv_obj_set_y(ui_LabelLungo1, 50);
    lv_obj_set_align(ui_LabelLungo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLungo1, "Lungo");
    lv_obj_add_flag(ui_LabelLungo1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_decor(ui_LabelLungo1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLungo1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Coffe1 = lv_label_create(ui_Pagamento);
    lv_obj_set_width(ui_Coffe1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Coffe1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Coffe1, 0);
    lv_obj_set_y(ui_Coffe1, -118);
    lv_obj_set_align(ui_Coffe1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Coffe1, "Coffe21");
    lv_obj_set_style_text_font(ui_Coffe1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Pagamento);
    lv_img_set_src(ui_Image1, &ui_img_barrainf_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 471
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 100);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Pagamento);
    lv_img_set_src(ui_Image6, &ui_img_voltar_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_Image6, -203);
    lv_obj_set_y(ui_Image6, -118);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Pagamento);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 80);
    lv_obj_set_y(ui_Label3, 79);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "621 sats");

    ui_Image7 = lv_img_create(ui_Pagamento);
    lv_img_set_src(ui_Image7, &ui_img_qrcode_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 148
    lv_obj_set_x(ui_Image7, 80);
    lv_obj_set_y(ui_Image7, -10);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);

}
