// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Inicial
void ui_Inicial_screen_init(void);
lv_obj_t * ui_Inicial;
void ui_event_expresso(lv_event_t * e);
lv_obj_t * ui_expresso;
void ui_event_lungo(lv_event_t * e);
lv_obj_t * ui_lungo;
lv_obj_t * ui_LabelExpresso;
lv_obj_t * ui_LabelLungo;
lv_obj_t * ui_Coffe21;
lv_obj_t * ui_Image4;


// SCREEN: ui_Pagamento
void ui_Pagamento_screen_init(void);
lv_obj_t * ui_Pagamento;
lv_obj_t * ui_expresso1;
lv_obj_t * ui_lungo1;
lv_obj_t * ui_LabelExpresso1;
lv_obj_t * ui_LabelLungo1;
lv_obj_t * ui_Coffe1;
lv_obj_t * ui_Image1;
void ui_event_Image6(lv_event_t * e);
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image7;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_logoc[1] = {&ui_img_logoc21_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_expresso(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Pagamento, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pagamento_screen_init);
        _ui_flag_modify(ui_expresso1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lungo1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_LabelExpresso1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_LabelLungo1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_lungo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pagamento, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pagamento_screen_init);
        _ui_flag_modify(ui_LabelLungo1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lungo1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_expresso1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_LabelExpresso1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Inicial, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Inicial_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Inicial_screen_init();
    ui_Pagamento_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Inicial);
}
